core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('menu.urls')),
]

menu/urls.py
from django.urls import path
from menu.views import index, draw_menu

app_name = 'menu'

urlpatterns = [
    path('', index, name='main_menu'),
    path('<str:menu_name>/', draw_menu, name='draw_menu'),
    path('<str:menu_name>/<str:menu_item>', draw_menu, name='draw_menu'),
    ]

menu/models.py
from django.db import models


class Menu(models.Model):
    name = models.CharField('Название меню', max_length=50, unique=True)
    url = models.CharField('Ссылка', max_length=255, blank=True)

    def __str__(self):
        return str(self.name)

    class Meta:
        ordering = ['name']
        verbose_name = 'Меню'
        verbose_name_plural = 'Меню'


class MenuItem(models.Model):
    name = models.CharField('Название пункта меню', max_length=100, unique=True)
    url = models.CharField('Ссылка', max_length=255, blank=True)
    parent = models.ForeignKey('self', blank=True, null=True, on_delete=models.CASCADE, related_name='children')
    menu = models.ForeignKey(Menu, on_delete=models.CASCADE, related_name='menu_items')

    def __str__(self):
        return str(self.name)

    class Meta:
        ordering = ['name']
        verbose_name = 'Пункт меню'
        verbose_name_plural = 'Пункты меню'

menu/views.py
from django.shortcuts import render

from menu.models import Menu


def index(request):
    return render(request, 'menu/index.html', {'menus': Menu.objects.all()})


def draw_menu(request, menu_name, menu_item=None):
    return render(request, 'menu/index.html', {'menu_name': menu_name, 'menu_item': menu_item})

menu/templates/menu/index.html
{% extends 'base.html' %}
{% load tree_tag %}
{% block content %}
    {% if menus %}
        <h3><a href="{% url 'menu:main_menu' %}">Список всех меню</a></h3>
        <ul>
            {% for menu in menus%}
                <li><a href='{{ menu }}'> {{ menu }}</a></li>
            {% endfor %}
        </ul>

    {% else %}
        <h3><a href="{% url 'menu:main_menu' %}">В список всех меню</a></h3>
        {% draw_menu menu_name %}

    {% endif %}
{% endblock %}

menu/templates/menu/menu_template.html
{% for item in menu_items %}
    <ul>
        <li {% if active_item and active_item == item.item.url %} style="color:red" class="active"{% endif %}>
            <a href="{{ item.item.url }}">{{ item.item.name }}</a>
        </li>
        {% if item.children %}
            {% with item.children as children %}
                {% include 'menu/menu_template.html' with menu_items=children active_item=active_item %}
            {% endwith %}
        {% endif %}
    </ul>
{% endfor %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>My site</title>
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>